// src/app/presentation/views/react/cards/cards-list/cards-list.tsx
import { Component } from "react";
import { CardPloc } from "src/app/presentation/ploc/cards/card.ploc";
import { CardState } from "src/app/presentation/ploc/cards/card.state";
import { CardsService } from "src/app/services/cards/cards.service";
import { GetCardUsecase } from "src/app/usecases/cards/get-cards.usecase";
import { LoadingState } from "./states/loading-state.component/loading-state";
import { ReceivingState } from "./states/receiving-state/receiving-state";

export class CardListComponent extends Component<any> {
  ploc: CardPloc;
  private _state: CardState;

  constructor(props: CardState) {
    super(props);
    this._state = {
      kind: "LoadingState",
    };
    this.ploc = new CardPloc(new GetCardUsecase(new CardsService()));
    this.ploc.subscribe((state: CardState) => {
      this._state = state;
      this.setState({})
    });
    this.ploc.init()
  }
  render() {

    switch (this._state.kind) {
      case "LoadingState":
        return <LoadingState />;

        case "ReceivingState":
          return <ReceivingState cards={this._state.cards}/>;

      default:
        return <LoadingState />;
    }
  }
}

// src/app/presentation/views/angular/cards/pages/cards-list/cards-list.component.ts
import {
  Component,
  ComponentFactoryResolver,
  OnInit,
  ViewContainerRef,
} from "@angular/core";
import { CardPloc } from "src/app/presentation/ploc/cards/card.ploc";
import { CardState } from "src/app/presentation/ploc/cards/card.state";
import { LoadedStateComponent } from "./states/loaded-state/loaded-state.component";
import { LoadingStateComponent } from "./states/loading-state/loading-state.component";
import { ReceivingStateComponent } from "./states/receiving-state/receiving-state.component";

@Component({
  selector: "kc-cards-list",
  templateUrl: "./cards-list.component.html",
  styleUrls: ["./cards-list.component.scss"],
})
export class CardsListComponent implements OnInit {
  static stateMapper: any = {
    LoadingState: LoadingStateComponent,
    LoadedState: LoadedStateComponent,
    ReceivingState: ReceivingStateComponent,
    default: LoadingStateComponent,
  };
  constructor(
    private viewContainerRef: ViewContainerRef,
    private componentFactoryResolver: ComponentFactoryResolver,
    private ploc: CardPloc
  ) {
    this.ploc.subscribe((state: CardState) => {
      this.setContent(state);
    });
  }

  ngOnInit(): void {
    this.ploc.init()
   
  }

  setContent(state: CardState) {
    let component: any;
    if (state.kind in CardsListComponent.stateMapper) {
      component = CardsListComponent.stateMapper[state.kind];
    } else {
      component = CardsListComponent.stateMapper["default"];
    }
    this.viewContainerRef.clear();
    const factory =
      this.componentFactoryResolver.resolveComponentFactory(component);
    const componentRef = this.viewContainerRef.createComponent(factory);
    (componentRef.instance as any).state = state
  }
}
