// src/app/presentation/views/angular/cards/pages/cards-list/states/receiving-state/receiving-state.component.ts
import { Component, OnInit } from "@angular/core";
import { ICardModel } from "src/app/entities/cards/card.model";
import { ReceivingState } from "src/app/presentation/ploc/cards/card.state";

@Component({
  selector: "kc-receiving-state",
  templateUrl: "./receiving-state.component.html",
  styleUrls: ["./receiving-state.component.scss"],
})
export class ReceivingStateComponent implements OnInit {
  state!: ReceivingState;
  cards!: ICardModel[];
  constructor() {}

  ngOnInit(): void {
    this.cards = this.state.cards;
  }
}

<section *ngFor="let card of cards">
  <figure>
    <img src="{{ card.preview }}" alt="" />
  </figure>
  <span>
    {{ card.name }}
  </span>
</section>

// src/app/presentation/views/react/cards/cards-list/states/receiving-state/receiving-state.tsx
import './receiving-state.scss'

export const ReceivingState = (data: any) => {
  console.log(data);
  return data.cards.map((x: any) => {
    const path = "./" + x.preview;
    return (
      <section>
        <figure>
          <img src={path} alt="" />
        </figure>
        <span>{x.name}</span>
      </section>
    );
  });
};
